bind 0.0.0.0
protected-mode yes
port 0
tls-port 6379
tls-cert-file /run/certs/redis.crt
tls-key-file /run/certs/redis.key
tls-ca-cert-file /run/certs/ca.pem
tls-auth-clients no
aclfile /run/redis-secrets/users.acl
save ""
appendonly no
loglevel warning
