<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>ume-llm-gateway-gateway</UserSecretsId>
    <ContainerRepository>ume-llm-gateway/gateway</ContainerRepository>
    <UmeServiceContainer>true</UmeServiceContainer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ume.LlmGateway.Infrastructure\Ume.LlmGateway.Infrastructure.csproj" />
    <ProjectReference Include="..\Ume.LlmGateway.ServiceDefaults\Ume.LlmGateway.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ume.LlmGateway.Gateway.Tests" />
    <InternalsVisibleTo Include="Ume.LlmGateway.Benchmarks" />
  </ItemGroup>
</Project>
