<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>ume-llm-gateway-dataapi</UserSecretsId>
    <ContainerRepository>ume-llm-gateway/dataapi</ContainerRepository>
    <UmeServiceContainer>true</UmeServiceContainer>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ume.LlmGateway.Infrastructure\Ume.LlmGateway.Infrastructure.csproj" />
    <ProjectReference Include="..\Ume.LlmGateway.ServiceDefaults\Ume.LlmGateway.ServiceDefaults.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Ume.LlmGateway.DataApi.Tests" />
  </ItemGroup>
</Project>
